#!/usr/bin/env python3
"""Lightweight project architecture checks generated by the Preset."""
from __future__ import annotations
import argparse, json, re
from pathlib import Path

SKIP = {"node_modules", ".git", "dist", "build", ".next", "coverage", ".turbo"}
GUARDED_BASENAMES = {"utils.ts", "helpers.ts", "common.ts", "service.ts", "manager.ts", "handler.ts", "handlers.ts", "types.ts"}
IMPORT_RE = re.compile(r"(?:from\s+|import\s*\()\s*[\"']([^\"']+)[\"']")

def files(root: Path):
    for p in root.rglob("*"):
        if any(part in SKIP for part in p.relative_to(root).parts):
            continue
        if p.suffix in {".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"} and p.is_file():
            yield p

def scan(root: Path):
    findings=[]
    for p in files(root):
        rel=p.relative_to(root).as_posix()
        text=p.read_text(encoding="utf-8", errors="ignore")
        if p.name in GUARDED_BASENAMES:
            findings.append({"severity":"warn","rule":"guarded-filename","path":rel,"message":"use a subject-qualified responsibility when possible"})
        imports=IMPORT_RE.findall(text)
        if ".use-case." in p.name and any(".live" in i for i in imports):
            findings.append({"severity":"error","rule":"use-case-imports-live","path":rel,"message":"use case must depend on a port, not a live implementation"})
        if ".policy." in p.name and any(token in i.lower() for i in imports for token in ("http", "pg", "prisma", "stripe", "sdk")):
            findings.append({"severity":"error","rule":"policy-imports-platform","path":rel,"message":"policy should remain pure or explicitly contextual"})
        if "/modules/" in "/"+rel and ".wiring" in " ".join(imports) and "/host/" not in "/"+rel:
            findings.append({"severity":"error","rule":"business-imports-wiring","path":rel,"message":"ordinary business modules should use public surfaces"})
        semantic = p.name
        for suffix in (".integration.test.ts", ".contract.test.ts", ".recovery.test.ts", ".test.ts", ".tsx", ".ts"):
            if semantic.endswith(suffix):
                semantic=semantic[:-len(suffix)]
                break
        if semantic.count(".")+1 > 5:
            findings.append({"severity":"warn","rule":"long-semantic-name","path":rel,"message":"review whether the name is compensating for a missing sub-boundary"})
    return findings

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--repo", default="."); args=ap.parse_args()
    root=Path(args.repo).resolve(); findings=scan(root)
    summary={"error":sum(x["severity"]=="error" for x in findings),"warn":sum(x["severity"]=="warn" for x in findings),"total":len(findings)}
    print(json.dumps({"summary":summary,"findings":findings}, indent=2))
    if summary["error"]: raise SystemExit(1)
if __name__ == "__main__": main()
